---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    name: kafka
  namespace: logging
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-cluster
