apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster
  namespace: logging
spec:
  selector:
    matchLabels:
      app: kafka-cluster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-cluster
        name: kafka-cluster
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-cluster.logging.svc.cluster.local:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster.logging.svc.cluster.local:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        image: wurstmeister/kafka:latest
        imagePullPolicy: IfNotPresent
        name: kafka-cluster
        ports:
        - containerPort: 9092
          protocol: TCP
      restartPolicy: Always
